### ISSUE TITLE
Error: unsupported protocol version

### ISSUE THREAD

**Issue by joex92** [twisttaan/NatsirtMC#4]
```console
$ ts-node src/index.ts
C:\Users\joex92\NatsirtMC\node_modules\minecraft-protocol\src\createClient.js:28
  if (!mcData) throw new Error(`unsupported protocol version: ${optVersion}`)
                     ^
Error: unsupported protocol version: 1.18.2
    at Object.createClient (C:\Users\joex92\NatsirtMC\node_modules\minecraft-protocol\src\createClient.js:28:22)
    at Object.createBot (C:\Users\joex92\NatsirtMC\node_modules\mineflayer\lib\loader.js:95:35)
    at Object.<anonymous> (C:\Users\joex92\NatsirtMC\src\index.ts:11:22)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Module.m._compile (C:\Users\joex92\NatsirtMC\node_modules\ts-node\src\index.ts:1371:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\joex92\NatsirtMC\node_modules\ts-node\src\index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
error Command failed with exit code 1.
```
how do I add support for new versions?

**Comment by tristancamejo** [comment]
You’ll need to update mineflayer, I completely forgot this project existed; I may get around to reworking this since I made this when I was so young to programming.

**Comment by joex92** [comment]
lol yeah, I noticed.... I actually looked up mineflayer and I'm now testing the library 🙃
I'm still learning node, so I didn't know how to update your project to make it work with the latest version of every module... 😅

**Comment by tristancamejo** [comment]
If you’re learning node, I strongly recommend not using this repo as a
reference. It uses some very bad practises for example usage of `ts-node`.

**Comment by joex92** [comment]
🤔 I mean, I noticed... that's why in the end I didn't try to update your code, although I still forked it just in case...
anyways a rework would be appreciated...
